### PR TITLE
Adding IPv6 support for the static network configuration.

### PR DESCRIPTION
**Pull request by mat1010**
Hi,
I added support for IPv6. Right now routes and aliases are not included in this change since this seems to be a bit different to the IPv4 syntax, but I will keep on working to get this implemented as well.

Would be great if you could take a look at it.

Thanks in advance,
Matthias

### CODE REVIEW

**Comment by razorsedge** [comment]
Awesome!

Would it be possible to add some rspec tests to this PR?  We have to keep Travis-CI happy.

**Comment by razorsedge** [comment]
Also, can you take a look at PR #32 and see if your PR will work with it?

**Comment by razorsedge** [comment]
And would it be possible to rebase this PR against razorsedge:develop?

**Comment by mat1010** [comment]
Hi,
> Would it be possible to add some rspec tests to this PR? We have to keep Travis-CI happy.

I never did this yet - but I'll check if I can get this done

> Also, can you take a look at PR #32 and see if your PR will work with it?

Yep - that one will work. It can be enabled as following

```puppet
class { 'network::global':
  ipv6networking => true,
}
```

> And would it be possible to rebase this PR against razorsedge:develop?

Working on the rebase

**Comment by mat1010** [comment]
The rebase is done - or do you want me to send the pull request against the develop branch?

**Comment by mat1010** [comment]
I added some new rspec tests and modified existing one to check for the ipv6 addresses as well.

**Comment by razorsedge** [comment]
Looks like you will have to send a PR against the develop branch.

**Comment by mat1010** [comment]
Ok - I will close this PR and upen a new one against the develop branch.

**Pull request closed without merging**
