### PR TITLE
Defined - NM_CONTROLLED, DEFROUTE, METRIC, ZONE

### PR DESCRIPTION
**Pull request by gorbyo**

### CODE REVIEW

**Comment by razorsedge** [comment]
@gorbyo Thank you for your submission. I would like to merge your PR, but I cannot accept the `nmcontrol` parameter.  The razorsedge/network module only manages the traditional RedHat network configuration mechanisms.  The value of `NM_CONTROLLED` needs to remain `no` otherwise we start interacting with NetworkManager.

Could you please resubmit without the `nmcontrol` parameter?

**Comment by gorbyo** [comment]
@razorsedge Thank you for your comment. I removed `nmcontrol` parameter and synced with current master branch.

**Comment by razorsedge** [comment]
@gorbyo Please remove commit 2a23d26a4218254ec245cf9a056929f5a0dfec08, I will not be able to merge changes that have already been merged.  If you need the fixes that are present, you should merge them into your branch from `develop`.

**Comment by gorbyo** [comment]
@razorsedge I fixed conflicts

**Pull request merged**
