### PR TITLE
Add hiera support for all defines

### PR DESCRIPTION
**Pull request by esalberg**

### CODE REVIEW

**Comment by razorsedge** [comment]
Nice!

My only complaint would be that I should not be listed as the author or copyrightee in the file header. can you put your name/details in there instead?

**Comment by anders-larsson** [comment]
Cool. Good work. I'll test on Monday!

**Comment by anders-larsson** [comment]
Works great. :)

**Comment by razorsedge** [comment]
@esalberg Ping?

**Comment by anders-larsson** [comment]
@esalberg @razorsedge bump. This would be a nice addition to this module :)

**Pull request merged**
