### PR TITLE
parameter to disable restart of network service on change

### PR DESCRIPTION
**Pull request by evgeni**
sometimes one might want to configure an interface, but not yet activate it. with this change you can pass `restart => false` to the interface definition and it will not trigger the restart of the network service.

### CODE REVIEW

**Comment by esalberg** [comment]
We need this as well.

**Comment by razorsedge** [comment]
Note: Needs README update.

**Comment by evgeni** [comment]
Updated README and rebased.

**Comment by razorsedge** [comment]
Merged in rebase commit f40e967.

**Pull request closed without merging**
