### PR TITLE
Adding IPv6 support for static and global network configuration

### PR DESCRIPTION
**Pull request by mat1010**
Hi,
would be great if you could take another look into this PR to the develop branch that I initially requested against the master within #50

Regards,
Matthias

### CODE REVIEW

**Comment by razorsedge** [comment]
This looks great.  Might I ask for one last thing?  Can you update the README.md with some details of how to use these settings?

**Comment by mat1010** [comment]
I made some minor changes on the documentation, more will follow. I will also add some more changes for IPv6 support on bridge interfaces plus the required tests for those change, I'm nearly done with those - but right now travis-ci seems tho have issue since the build after my documentation update already failed for whatever reason - do you know the reason for this?

**Comment by razorsedge** [comment]
I won't be able to look into the Travis failures until tonight.

**Comment by razorsedge** [comment]
It looks like the failures are linked with using rspec 3 and not rspec 2 with Ruby 1.8.7. I am working on converting to rspec-puppet >= 2.0.0 (which pins to rspec 2.x).

**Comment by mat1010** [comment]
Great, thanks.

**Comment by razorsedge** [comment]
Spec tests are working again.  If you `git rebase` from `develop`, you should get commits eadb26513f474b3fbba62e76e32300965e166e7d and 2bd6ca9190726c4449914ea420dd8a9cf4ded22f.

**Comment by mat1010** [comment]
I accidentaly rebased against the master -.- I will work on fixing this.

**Comment by mat1010** [comment]
Since I totally messed up the rebase I will reimplement my changes into the latest devel. branch.

**Pull request closed without merging**
