### PR TITLE
Add peerdns and check_link_down for dynamic interfaces; add logic for…

### PR DESCRIPTION
**Pull request by esalberg**
… blank ipaddress, network, gateway to remove extra entries from ifcfg file; minor lint and comments cleanup

### CODE REVIEW

**Comment by esalberg** [comment]
Re-requested against develop.

**Comment by esalberg** [comment]
I realized that I did not have the updated template logic to handle blank ( '' ) macaddress entries from network_bond_static and network_bond_dynamic without having an empty HWADDR= line.  Since I already had the same template patch here for the the other three affected template entries, I did a second commit to add HWADDR.

I checked the spec, and I don't think anything there needs updating.

Please let me know if you need me either to pull the template changes into a separate pull request (I'd prefer not for the extra work, but I understand why I might need to do that :) ), or if you need me to squash the commits.

**Comment by esalberg** [comment]
I just noticed that develop was updated - just let me know if my update here needs to be moved. :)

**Comment by razorsedge** [comment]
Does commit f5b1bd40264ecd4b61d218332877e162649b37c7 address PRs #42 and #69?

**Pull request merged**
