### PR TITLE
Hiera

### PR DESCRIPTION
**Pull request by esalberg**
Add hiera support for existing 14 defines.  Update README.md

### CODE REVIEW

**Comment by esalberg** [comment]
I tried rebasing again to get down to 1 commit, but it still shows your merge as well as my commit.  Let me know if I need to fix anything.

**Comment by razorsedge** [comment]
@esalberg resubmit against `develop` and not `master`.

**Comment by esalberg** [comment]
Ugh, my VPN is slow and the drop-down click didn't work. :/  At least it explains the extra commit!  Resubmitted as PR #78

**Comment by razorsedge** [comment]
Nice!

My only complaint would be that I should not be listed as the author or copyrightee in the file header.  can you put your name/details in there instead?

**Pull request closed without merging**
